name = "cm-rarity-api"
main = "backend/worker.js"
compatibility_date = "2026-05-22"

[observability]
enabled = true

[[d1_databases]]
binding = "CM_DB"
database_name = "cm-rarity-prod"
database_id = "5a66493d-f2e7-4ee5-8ebb-62eb1fb497ef"
